defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: "_pages"
      type: "pages"
    values:
      permalink: "/:basename"
include: ['_pages']
paths:
  photos: "/media/photos"
  videos: "/media/videos"